# Exp 1: Breadth First Search

In [2]:
graph = {
  'A' : ['B','C'],
  'B' : ['D', 'E'],
  'C' : ['F'],
  'D' : [],
  'E' : [],
  'F' : []
}

visited = [] 
queue = []  

def bfs(visited, graph, node): 
  visited.append(node)
  queue.append(node)

  while queue:          
    m = queue.pop(0) 
    print (m, end = " ") 

    for neighbour in graph[m]:
      if neighbour not in visited:
        visited.append(neighbour)
        queue.append(neighbour)

print("Following is the Breadth-First Search")
bfs(visited, graph, 'A')

Following is the Breadth-First Search
A B C D E F 

# EXP 2: Depth First Search 

In [3]:
graph = {
  'A' : ['B','C'],
  'B' : ['D', 'E'],
  'C' : ['F'],
  'D' : [],
  'E' : ['F'],
  'F' : []
}

visited = set() # Set to keep track of visited nodes of graph.

def dfs(visited, graph, node):  #function for dfs 
    if node not in visited:
        print (node)
        visited.add(node)
        for neighbour in graph[node]:
            dfs(visited, graph, neighbour)

# Driver Code
print("Following is the Depth-First Search")
dfs(visited, graph, 'A')

Following is the Depth-First Search
A
B
D
E
F
C


# Exp 3 :1/0 KnapSack algo(Gready)

In [5]:
def knapSack(W, wt, val, n):
    K = [[0 for x in range(W + 1)] for x in range(n + 1)]
    for i in range(n + 1):
        for w in range(W + 1):
            if i == 0 or w == 0:
                K[i][w] = 0
            elif wt[i-1] <= w:
                K[i][w] = max(val[i-1] + K[i-1][w-wt[i-1]], K[i-1][w])
            else:
                K[i][w] = K[i-1][w]
    return K[n][W]
val = [60, 100, 120]
wt = [10, 20, 30]
W = 50
n = len(val)
print(knapSack(W, wt, val, n))

220


# EXP 4: A Star algo(Heuristic Search)

In [6]:
def aStarAlgo(start_node, stop_node):
        open_set = set(start_node) 
        closed_set = set()
        g = {} 
        parents = {}
        g[start_node] = 0
        parents[start_node] = start_node
        while len(open_set) > 0:
            n = None
            for v in open_set:
                if n == None or g[v] + heuristic(v) < g[n] + heuristic ( n ):
                    n = v
            if n == stop_node or Graph_nodes[n] == None:
                pass
            else:
                for (m, weight) in get_neighbors ( n ):
                    if m not in open_set and m not in closed_set:
                        open_set.add(m)
                        parents[m] = n
                        g[m] = g[n] + weight
                    else:
                        if g[m] > g[n] + weight:
                            g[m] = g[n] + weight
                            parents[m] = n
                            if m in closed_set:
                                closed_set.remove(m)
                                open_set.add(m)
            if n == None:
                print('Path does not exist!')
                return None
            if n == stop_node:
                path = []
                while parents[n] != n:
                    path.append( n )
                    n = parents[n]
                path.append(start_node)
                path.reverse()
                print('Path found: {}'.format(path))
                return path
            open_set.remove( n )
            closed_set.add( n )
        print('Path does not exist!')
        return None
def get_neighbors(v):
    if v in Graph_nodes:
        return Graph_nodes[v]
    else:
        return None
def heuristic ( n ):
        H_dist = {
            'A': 11,
            'B': 6,
            'C': 99,
            'D': 1,
            'E': 7,
            'G': 0,
        }
        return H_dist[n]
Graph_nodes = {
    'A': [('B', 2), ('E', 3)],
    'B': [('C', 1),('G', 9)],
    'C': None,
    'E': [('D', 6)],
    'D': [('G', 1)],
}
aStarAlgo('A', 'G')

Path found: ['A', 'E', 'D', 'G']


['A', 'E', 'D', 'G']

# Exp 5: Traveling Salesman Problem

In [13]:
# Python3 program to implement traveling salesman
# problem using naive approach.
from sys import maxsize
from itertools import permutations
V = 4
# implementation of traveling Salesman Problem
def travellingSalesmanProblem(graph, s):
	# store all vertex apart from source vertex
    vertex = []
    for i in range(V):
        if i != s:
            vertex.append(i)
	# store minimum weight Hamiltonian Cycle
    min_path = maxsize
    next_permutation=permutations(vertex)
    for i in next_permutation:
		# store current Path weight(cost)
        current_pathweight = 0
		# compute current path weight
        k = s
        for j in i:
            current_pathweight += graph[k][j]
            k = j
        current_pathweight += graph[k][s]
		# update minimum
        min_path = min(min_path, current_pathweight)
    return min_path
# Driver Code
if __name__ == "__main__":
	# matrix representation of graph
    graph = [[0, 10, 15, 20], [10, 0, 35, 25],
            [15, 35, 0, 30], [20, 25, 30, 0]]
    s = 0
    print(travellingSalesmanProblem(graph, s))


80


# EXP 6: 8-Puzzle problem using Python

In [14]:
class Solution:
   def solve(self, board):
      dict = {}
      flatten = []
      for i in range(len(board)):
         flatten += board[i]
      flatten = tuple(flatten)

      dict[flatten] = 0

      if flatten == (0, 1, 2, 3, 4, 5, 6, 7, 8):
         return 0

      return self.get_paths(dict)

   def get_paths(self, dict):
      cnt = 0
      while True:
         current_nodes = [x for x in dict if dict[x] == cnt]
         if len(current_nodes) == 0:
            return -1

         for node in current_nodes:
            next_moves = self.find_next(node)
            for move in next_moves:
               if move not in dict:
                  dict[move] = cnt + 1
               if move == (0, 1, 2, 3, 4, 5, 6, 7, 8):
                  return cnt + 1
         cnt += 1

   def find_next(self, node):
      moves = {
         0: [1, 3],
         1: [0, 2, 4],
         2: [1, 5],
         3: [0, 4, 6],
         4: [1, 3, 5, 7],
         5: [2, 4, 8],
         6: [3, 7],
         7: [4, 6, 8],
         8: [5, 7],
      }

      results = []
      pos_0 = node.index(0)
      for move in moves[pos_0]:
         new_node = list(node)
         new_node[move], new_node[pos_0] = new_node[pos_0], new_node[move]
         results.append(tuple(new_node))

      return results
ob = Solution()
matrix = [
   [3, 1, 2],
   [4, 7, 5],
   [6, 8, 0]
]
print(ob.solve(matrix))

4


# Exp 7:Monkey Banana Problem

In [20]:
def monkey_banana_problem(n, m, move_cost, jump_cost):
    # Create a 2D table to store the minimum cost
    dp = [[0] * (m + 1) for _ in range(n + 1)]
    
    # Initialize the first row and column
    for i in range(1, n + 1):
        dp[i][0] = i * move_cost
    for j in range(1, m + 1):
        dp[0][j] = j * jump_cost
    
    # Fill in the rest of the table
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            # Calculate the cost of moving to the current cell
            move_to_current = dp[i - 1][j] + move_cost
            
            # Calculate the cost of jumping to the current cell
            jump_to_current = dp[i][j - 1] + jump_cost
            
            # Take the minimum cost between moving and jumping
            dp[i][j] = min(move_to_current, jump_to_current)
    
    # Return the minimum cost to reach the bananas
    return dp[n][m]

# Example usage
n = 3  # Number of moves
m = 4  # Number of jumps
move_cost = 1  # Cost of moving
jump_cost = 2  # Cost of jumping

min_cost = monkey_banana_problem(n, m, move_cost, jump_cost)
print("Minimum cost to reach the bananas:", min_cost)

Minimum cost to reach the bananas: 11


# EXP 8: Hangman Problem 

In [21]:
import random

# List of words to choose from
word_list = ["apple", "banana", "cherry", "durian", "elderberry", "fig", "grapefruit", "honeydew"]

def hangman():
    # Choose a random word from the word_list
    word = random.choice(word_list)

    # Set up variables
    guessed_letters = []
    tries = 6

    # Loop until the game is over
    while True:
        # Display the current state of the word
        display_word = ""
        for letter in word:
            if letter in guessed_letters:
                display_word += letter + " "
            else:
                display_word += "_ "
        print(display_word)

        # Check if the player has guessed all the letters
        if "_" not in display_word:
            print("Congratulations! You guessed the word correctly!")
            break

        # Get the player's guess
        guess = input("Guess a letter: ").lower()

        # Check if the guess is a single letter
        if len(guess) != 1 or not guess.isalpha():
            print("Please enter a single letter.")
            continue

        # Check if the letter has already been guessed
        if guess in guessed_letters:
            print("You have already guessed that letter.")
            continue

        # Add the guessed letter to the list
        guessed_letters.append(guess)

        # Check if the guessed letter is in the word
        if guess in word:
            print("Good guess!")
        else:
            print("Wrong guess!")
            tries -= 1

        # Check if the player has run out of tries
        if tries == 0:
            print("You have run out of tries. The word was:", word)
            break

        # Display the remaining tries
        print("Tries left:", tries)
        print()

# Start the game
print("Welcome to Hangman!")
hangman()


Welcome to Hangman!
_ _ _ _ _ _ 
Guess a letter: t
Wrong guess!
Tries left: 5

_ _ _ _ _ _ 
Guess a letter: w
Wrong guess!
Tries left: 4

_ _ _ _ _ _ 
Guess a letter: w
You have already guessed that letter.
_ _ _ _ _ _ 
Guess a letter: g
Wrong guess!
Tries left: 3

_ _ _ _ _ _ 
Guess a letter: a
Good guess!
Tries left: 3

_ _ _ _ a _ 
Guess a letter: g
You have already guessed that letter.
_ _ _ _ a _ 
Guess a letter: 
Please enter a single letter.
_ _ _ _ a _ 
Guess a letter: s
Wrong guess!
Tries left: 2

_ _ _ _ a _ 
Guess a letter: d
Good guess!
Tries left: 2

d _ _ _ a _ 
Guess a letter: u
Good guess!
Tries left: 2

d u _ _ a _ 
Guess a letter: r
Good guess!
Tries left: 2

d u r _ a _ 
Guess a letter: i
Good guess!
Tries left: 2

d u r i a _ 
Guess a letter: m
Wrong guess!
Tries left: 1

d u r i a _ 
Guess a letter: n
Good guess!
Tries left: 1

d u r i a n 
Congratulations! You guessed the word correctly!


# Water Jug Problem

In [22]:
def water_jug_problem(jug1_capacity, jug2_capacity, target_amount):
    # Initial state of the jugs
    jug1 = 0
    jug2 = 0

    # Set of visited states to avoid loops
    visited = set()

    # Queue for BFS
    queue = [(jug1, jug2, [])]

    while queue:
        jug1, jug2, path = queue.pop(0)

        # Check if the target amount is reached
        if jug1 == target_amount or jug2 == target_amount:
            if jug1 == target_amount:
                path.append(f"Fill Jug 1 ({jug1_capacity}L)")
            else:
                path.append(f"Fill Jug 2 ({jug2_capacity}L)")
            return path

        # Generate possible actions
        actions = [
            ("Fill Jug 1", jug1_capacity, jug2),
            ("Fill Jug 2", jug1, jug2_capacity),
            ("Empty Jug 1", 0, jug2),
            ("Empty Jug 2", jug1, 0),
            ("Pour Jug 1 to Jug 2", max(0, jug1 - (jug2_capacity - jug2)), min(jug2 + jug1, jug2_capacity)),
            ("Pour Jug 2 to Jug 1", min(jug1 + jug2, jug1_capacity), max(0, jug2 - (jug1_capacity - jug1)))
        ]

        for action, new_jug1, new_jug2 in actions:
            if (new_jug1, new_jug2) not in visited:
                visited.add((new_jug1, new_jug2))
                queue.append((new_jug1, new_jug2, path + [action]))

    return None

# Example usage
jug1_capacity = 5
jug2_capacity = 3
target_amount = 4

result = water_jug_problem(jug1_capacity, jug2_capacity, target_amount)
if result:
    print("Steps to measure the target amount of water:")
    for step in result:
        print(step)
else:
    print("Cannot measure the target amount of water with the given jug capacities.")


Steps to measure the target amount of water:
Fill Jug 1
Pour Jug 1 to Jug 2
Empty Jug 2
Pour Jug 1 to Jug 2
Fill Jug 1
Pour Jug 1 to Jug 2
Fill Jug 1 (5L)


In [23]:
# Tic-Tac-Toe board
board = [' ' for _ in range(9)]

# Winning combinations
winning_combinations = [
    (0, 1, 2), (3, 4, 5), (6, 7, 8),  # Rows
    (0, 3, 6), (1, 4, 7), (2, 5, 8),  # Columns
    (0, 4, 8), (2, 4, 6)              # Diagonals
]

# Current player ('X' or 'O')
current_player = 'X'

# Function to print the Tic-Tac-Toe board
def print_board():
    print('-------------')
    for i in range(0, 9, 3):
        print(f'| {board[i]} | {board[i + 1]} | {board[i + 2]} |')
        print('-------------')

# Function to check if any player has won
def check_winner():
    for combination in winning_combinations:
        if board[combination[0]] == board[combination[1]] == board[combination[2]] != ' ':
            return True
    return False

# Function to play the Tic-Tac-Toe game
def play_game():
    print('Welcome to Tic-Tac-Toe!')
    print_board()

    while True:
        position = int(input(f"Player {current_player}, choose a position (1-9): ")) - 1

        if board[position] == ' ':
            board[position] = current_player
            print_board()

            if check_winner():
                print(f'Player {current_player} wins!')
                break

            if ' ' not in board:
                print("It's a tie!")
                break

            # Switch players
            current_player = 'O' if current_player == 'X' else 'X'
        else:
            print('That position is already filled. Choose a different position.')

# Start the game
play_game()


Welcome to Tic-Tac-Toe!
-------------
|   |   |   |
-------------
|   |   |   |
-------------
|   |   |   |
-------------


UnboundLocalError: local variable 'current_player' referenced before assignment

In [24]:
# Tic-Tac-Toe Program using
# random number in Python

# importing all necessary libraries
import numpy as np
import random
from time import sleep

# Creates an empty board


def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))

# Check for empty places on board


def possibilities(board):
	l = []

	for i in range(len(board)):
		for j in range(len(board)):

			if board[i][j] == 0:
				l.append((i, j))
	return(l)

# Select a random place for the player


def random_place(board, player):
	selection = possibilities(board)
	current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)

# Checks whether the player has three
# of their marks in a horizontal row


def row_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a vertical row


def col_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a diagonal row


def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win

# Evaluates whether there is
# a winner or a tie


def evaluate(board):
	winner = 0

	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):

			winner = player

	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner

# Main function to start the game


def play_game():
	board, winner, counter = create_board(), 0, 1
	print(board)
	sleep(2)

	while winner == 0:
		for player in [1, 2]:
			board = random_place(board, player)
			print("Board after " + str(counter) + " move")
			print(board)
			sleep(2)
			counter += 1
			winner = evaluate(board)
			if winner != 0:
				break
	return(winner)


# Driver Code
print("Winner is: " + str(play_game()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Board after 2 move
[[1 0 0]
 [2 0 0]
 [0 0 0]]
Board after 3 move
[[1 0 1]
 [2 0 0]
 [0 0 0]]
Board after 4 move
[[1 2 1]
 [2 0 0]
 [0 0 0]]
Board after 5 move
[[1 2 1]
 [2 0 0]
 [0 0 1]]
Board after 6 move
[[1 2 1]
 [2 0 2]
 [0 0 1]]
Board after 7 move
[[1 2 1]
 [2 0 2]
 [1 0 1]]
Board after 8 move
[[1 2 1]
 [2 0 2]
 [1 2 1]]
Board after 9 move
[[1 2 1]
 [2 1 2]
 [1 2 1]]
Winner is: 1
